### ISSUE TITLE
NzeHvac issue with 3.8-rc2 testing

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-ee-gem#53]
All 12 test fail have this same failure. Failure: test_office_radiant_doas(Minitest::Result) [/srv/jenkins/git/openstudio-ee-gem/PR-52/10/lib/measures/nze_hvac/measure.rb:348]: NoMethodError: undefined method `thermal_zone_plenum?'

Here is code
https://github.com/NREL/openstudio-ee-gem/blob/0.10.0-rc1/lib/measures/nze_hvac/measure.rb#L348

Work on [0.10.0-rc1 ](https://github.com/NREL/openstudio-ee-gem/tree/0.10.0-rc1) branch that I have PR on.

**Comment by DavidGoldwasser** [comment]
@mdahlhausen that error went away, but this one shows up now.

`NoMethodError: undefined method `model_annual_occupied_unmet_heating_hours`

**Comment by mdahlhausen** [comment]
@DavidGoldwasser all of these methods were moved to modules. Do you want to change those, or should I?

**Comment by DavidGoldwasser** [comment]
Down to three failed test now with similar error to this

`
Failure: test_humid_office_vav_reheat_auto_partition(Minitest::Result) [/srv/jenkins/git/openstudio-ee-gem/PR-52/13/.bundle/install/ruby/3.2.0/bundler/gems/openstudio-standards-a5fba7be1573/lib/openstudio-standards/geometry/group.rb:60]: ArgumentError: wrong number of arguments (given 2, expected 1) /srv/jenkins/git/openstudio-ee-gem/PR-52/13/.bundle/install/ruby/3.2.0/bundler/gems/openstudio-standards-a5fba7be1573/lib/openstudio-standards/geometry/group.rb:60:in `model_group_thermal_zones_by_occupancy_type' /srv/jenkins/git/openstudio-ee-gem/PR-52/13/lib/measures/nze_hvac/measure.rb:359:in `run' /srv/jenkins/git/openstudio-ee-gem/PR-52/13/lib/measures/nze_hvac/tests/NZEHVAC_Test.rb:109:in `run_nze_hvac_measure_test' /srv/jenkins/git/openstudio-ee-gem/PR-52/13/lib/measures/nze_hvac/tests/NZEHVAC_Test.rb:352:in `test_humid_office_vav_reheat_auto_partition'
`

**Comment by DavidGoldwasser** [comment]
Down to two with this error.

`
Failure: test_humid_office_vav_reheat_auto_partition(Minitest::Result) [/srv/jenkins/git/openstudio-ee-gem/PR-52/14/.bundle/install/ruby/3.2.0/bundler/gems/openstudio-standards-a5fba7be1573/lib/openstudio-standards/geometry/group.rb:60]: ArgumentError: unknown keyword: :min_ara_m2 /srv/jenkins/git/openstudio-ee-gem/PR-52/14/.bundle/install/ruby/3.2.0/bundler/gems/openstudio-standards-a5fba7be1573/lib/openstudio-standards/geometry/group.rb:60:in `model_group_thermal_zones_by_occupancy_type' /srv/jenkins/git/openstudio-ee-gem/PR-52/14/lib/measures/nze_hvac/measure.rb:359:in `run' /srv/jenkins/git/openstudio-ee-gem/PR-52/14/lib/measures/nze_hvac/tests/NZEHVAC_Test.rb:109:in `run_nze_hvac_measure_test' /srv/jenkins/git/openstudio-ee-gem/PR-52/14/lib/measures/nze_hvac/tests/NZEHVAC_Test.rb:352:in `test_humid_office_vav_reheat_auto_partition'
--


<br class="Apple-interchange-newline">`
